name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Docs-Build
        run: |
          cd packages/hooks
          pnpm install --frozen-lockfile
          pnpm run initial
          pnpm run docs:build
      - name: Test
        run: |
          cd packages/hooks
          pnpm run test
      - name: Build
        run: |
          cd packages/hooks
          pnpm run build
        env:
          CI: true
